name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secrets-scan:
    name: Secret Leak Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Tells Git to look at the whole history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --staged --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Security scan version 1.0
